import { IonCol, IonGrid, IonIcon, IonItem, IonList, IonRow, IonText } from "@ionic/react";
import { mapOutline } from "ionicons/icons";

export const MapsContent = () => {
  const mapIDs = [
    { id: "115", type: "jpeg" },
    { id: "116", type: "png" },
    { id: "117", type: "png" },
    { id: "118", type: "png" },
    { id: "119", type: "png" },
    { id: "120", type: "png" },
    { id: "121", type: "png" },
    { id: "122", type: "png" },
    { id: "123", type: "png" },
    { id: "124", type: "png" },
    { id: "125", type: "png" },
    { id: "126", type: "png" },
    { id: "127", type: "png" },
    { id: "128", type: "png" },
    { id: "129", type: "png" },
    { id: "201", type: "png" },
    { id: "203", type: "jpeg" },
    { id: "204", type: "jpeg" },
    { id: "205", type: "jpeg" },
    { id: "206", type: "jpeg" },
    { id: "207", type: "jpeg" },
    { id: "208", type: "jpeg" },
    { id: "209", type: "jpeg" },
    { id: "210", type: "jpeg" },
    { id: "211", type: "jpeg" },
    { id: "301", type: "jpeg" },
    { id: "302", type: "png" },
    { id: "303", type: "jpeg" },
    { id: "304", type: "jpeg" },
    { id: "305", type: "jpeg" },
    { id: "306", type: "jpeg" },
    { id: "401", type: "png" },
    { id: "402", type: "jpeg" },
    { id: "403", type: "jpeg" },
    { id: "404", type: "jpeg" },
    { id: "405", type: "jpeg" },
    { id: "501", type: "jpeg" },
    { id: "502", type: "jpeg" },
    { id: "503", type: "jpeg" },
    { id: "504", type: "jpeg" },
    { id: "505", type: "jpeg" },
    { id: "506", type: "jpeg" },
    { id: "507", type: "jpeg" },
    { id: "508", type: "jpeg" },
    { id: "509", type: "jpeg" },
    { id: "510", type: "jpeg" },
    { id: "511", type: "jpeg" },
    { id: "512", type: "png" },
    { id: "514", type: "png" },
    { id: "601", type: "jpeg" },
    { id: "602", type: "jpeg" },
    { id: "701", type: "jpeg" },
    { id: "702", type: "jpeg" },
    { id: "703", type: "png" },
    { id: "704", type: "jpeg" },
    { id: "705", type: "jpeg" },
    { id: "706", type: "jpeg" },
    { id: "707", type: "jpeg" },
    { id: "708", type: "jpeg" },
    { id: "709", type: "jpeg" },
    { id: "710", type: "jpeg" },
    { id: "711", type: "png" },
    { id: "712", type: "png" },
    { id: "713", type: "jpeg" },
    { id: "714", type: "jpeg" },
    { id: "715", type: "jpeg" },
    { id: "801", type: "jpeg" },
    { id: "802", type: "png" },
    { id: "803", type: "png" },
    { id: "804", type: "jpeg" },
    { id: "805", type: "jpeg" },
    { id: "806", type: "jpeg" },
    { id: "807", type: "jpeg" },
    { id: "808", type: "png" },
    { id: "809", type: "png" },
    { id: "810", type: "png" },
    { id: "901", type: "png" },
    { id: "902", type: "png" },
    { id: "903", type: "png" },
    { id: "1001", type: "png" },
    { id: "1002", type: "jpeg" },
    { id: "1003", type: "jpeg" },
    { id: "1004", type: "jpeg" },
    { id: "1101", type: "png" },
    { id: "1102", type: "jpeg" },
    { id: "1103", type: "jpeg" },
    { id: "1104", type: "jpeg" },
    { id: "1105", type: "jpeg" },
    { id: "1106", type: "jpeg" },
    { id: "1107", type: "jpeg" },
    { id: "1108", type: "jpeg" },
    { id: "1109", type: "jpeg" },
    { id: "1110", type: "jpeg" },
    { id: "1201", type: "jpeg" },
    { id: "1202", type: "jpeg" },
    { id: "1301", type: "jpeg" },
    { id: "1302", type: "jpeg" },
    { id: "1303", type: "jpeg" },
    { id: "1304", type: "jpeg" },
    { id: "1305", type: "jpeg" },
    { id: "1306", type: "jpeg" },
    { id: "1307", type: "jpeg" },
    { id: "1308", type: "jpeg" },
    { id: "1401", type: "jpeg" },
    { id: "1402", type: "jpeg" },
    { id: "1403", type: "jpeg" },
    { id: "1404", type: "jpeg" },
    { id: "1405", type: "jpeg" },
    { id: "1406", type: "jpeg" },
    { id: "1407", type: "jpeg" },
    { id: "1408", type: "jpeg" },
    { id: "1409", type: "jpeg" },
    { id: "1410", type: "jpeg" },
    { id: "1411", type: "jpeg" },
    { id: "1412", type: "jpeg" },
    { id: "1413", type: "jpeg" },
    { id: "1414", type: "jpeg" },
    { id: "1415", type: "jpeg" },
    { id: "1416", type: "png" },
    { id: "1417", type: "jpeg" },
    { id: "1418", type: "png" },
    { id: "1501", type: "jpeg" },
    { id: "1502", type: "jpeg" },
    { id: "1503", type: "jpeg" },
    { id: "1504", type: "jpeg" },
    { id: "1505", type: "jpeg" },
    { id: "1506", type: "jpeg" },
    { id: "1507", type: "jpeg" },
    { id: "1508", type: "jpeg" },
    { id: "1509", type: "jpeg" },
    { id: "1510", type: "jpeg" },
    { id: "1511", type: "jpeg" },
    { id: "1512", type: "jpeg" },
    { id: "1513", type: "jpeg" },
    { id: "1514", type: "png" },
    { id: "1601", type: "png" },
    { id: "1602", type: "png" },
    { id: "1701", type: "jpeg" },
    { id: "1702", type: "jpeg" },
    { id: "1801", type: "jpeg" },
    { id: "1901", type: "png" },
    { id: "1902", type: "png" },
    { id: "1903", type: "png" },
    { id: "2001", type: "jpeg" },
    { id: "2002", type: "jpeg" },
    { id: "2003", type: "jpeg" },
    { id: "2004", type: "jpeg" },
    { id: "2005", type: "png" },
    { id: "2006", type: "jpeg" },
    { id: "2007", type: "jpeg" },
    { id: "2008", type: "jpeg" },
    { id: "2009a", type: "png" },
    { id: "2009b", type: "png" },
    { id: "2010", type: "png" },
    { id: "2011", type: "jpeg" },
    { id: "2012", type: "jpeg" },
    { id: "2013a", type: "png" },
    { id: "2013b", type: "png" },
    { id: "2013c", type: "png" },
    { id: "2014", type: "png" },
    { id: "2015", type: "png" },
    { id: "2016", type: "png" },
    { id: "2017", type: "png" },
    { id: "2018a", type: "png" },
    { id: "2018b", type: "png" },
    { id: "2019a", type: "png" },
    { id: "2019b", type: "png" },
    { id: "2020", type: "jpeg" },
    { id: "2021", type: "jpeg" },
    { id: "2022", type: "jpeg" },
    { id: "2023", type: "png" },
    { id: "2024", type: "png" },
    { id: "2029", type: "png" },
    { id: "2030", type: "jpeg" },
    { id: "2031a", type: "png" },
    { id: "2031b", type: "png" },
    { id: "3001", type: "png" },
    { id: "3002", type: "png" },
  ];

  return (
    <>
      <IonList>
        {mapIDs.map((m) => {
          return (
            <IonGrid key={m.id} className="ion-no-padding">
              <IonRow>
                <IonCol>
                  <IonItem
                    lines="full"
                    routerLink={`/ministry/maps/detail/${m.id}/${m.type}`}
                    className="ion-margin-start"
                  >
                    <IonIcon slot="start" icon={mapOutline}></IonIcon>
                    <IonText>
                      <strong>{m.id}</strong>
                    </IonText>
                  </IonItem>
                </IonCol>
              </IonRow>
            </IonGrid>
          );
        })}
      </IonList>
      <div style={{ height: "15rem" }}></div>
    </>
  );
};
