import { z } from "zod";

export const midweekMeetingDataSchema = z.object({
  week_id: z.string(),
  mwb_week_date_locale: z.string().nullable().optional(),
  mwb_weekly_bible_reading: z.string(),
  mwb_song_first: z.number().int(),
  mwb_tgw_talk: z.string(),
  mwb_tgw_talk_title: z.string().nullable().optional(),
  mwb_tgw_gems_title: z.string().nullable().optional(),
  mwb_tgw_bread: z.string(),
  mwb_tgw_bread_title: z.string().nullable().optional(),
  mwb_ayf_count: z.number().int(),
  mwb_ayf_part1: z.string(),
  mwb_ayf_part1_time: z.number().int().nullable().optional(),
  mwb_ayf_part1_type: z.string().nullable().optional(),
  mwb_ayf_part1_title: z.string().nullable().optional(),
  mwb_ayf_part2: z.string(),
  mwb_ayf_part2_time: z.number().int().nullable().optional(),
  mwb_ayf_part2_type: z.string().nullable().optional(),
  mwb_ayf_part2_title: z.string().nullable().optional(),
  mwb_ayf_part3: z.string(),
  mwb_ayf_part3_time: z.number().int().nullable().optional(),
  mwb_ayf_part3_type: z.string().nullable().optional(),
  mwb_ayf_part3_title: z.string().nullable().optional(),
  mwb_ayf_part4: z.string().nullable().optional(),
  mwb_ayf_part4_time: z.number().int().nullable().optional(),
  mwb_ayf_part4_type: z.string().nullable().optional(),
  mwb_ayf_part4_title: z.string().nullable().optional(),
  mwb_song_middle: z.string().nullable().optional(),
  mwb_lc_count: z.number().int(),
  mwb_lc_part1: z.string(),
  mwb_lc_part1_time: z.number().int().nullable().optional(),
  mwb_lc_part1_content: z.string().nullable().optional(),
  mwb_lc_part1_title: z.string().nullable().optional(),
  mwb_lc_part2: z.string().nullable().optional(),
  mwb_lc_part2_time: z.number().int().nullable().optional(),
  mwb_lc_part2_content: z.string().nullable().optional(),
  mwb_lc_part2_title: z.string().nullable().optional(),
  mwb_lc_cbs: z.string(),
  mwb_lc_cbs_title: z.string().nullable().optional(),
  mwb_song_conclude: z.string().nullable().optional(),
});

export type MidweekMeetingData = z.infer<typeof midweekMeetingDataSchema>;
