export const localStorageKeys = {
  themeMode: "theme_mode",
  fontSize: "font_size",
  authToken: "auth_token",
  mapViewLocation: "map_view",
  selectedCongregation: "selected_congregation",
  selectedPublisher: "selected_publisher",
  filterSortPresets: "filter_sort_presets",
  filterSortActivePreset: "filter_sort_active_preset",
  publisherGenderFilter: "publisher_gender_filter",
  publisherSortOrder: "publisher_sort_order",
  screenshotSettings: "screenshot_settings",
  mapStyle: "map_style",
  customLocalStyleSettings: "custom_local_style_settings",
  doorToDoorForm: "door_to_door_form",
  recentMaps: "recent_maps",
  mapDisplayMode: "map_display_mode",
  selectedMapId: "selected_map_id",
  avFilterSortPresets: "av_filter_sort_presets",
  avFilterSortActivePreset: "av_filter_sort_active_preset",
  bulkEntryMapId: "bulk_entry_map_id",
  recentMapPublishers: "recent_map_publishers",
  mapLogFilterSortPresets: "map_log_filter_sort_presets",
  mapLogFilterSortActivePreset: "map_log_filter_sort_active_preset",
  ministryMapFilterSortPresets: "ministry_map_filter_sort_presets",
  ministryMapFilterSortActivePreset: "ministry_map_filter_sort_active_preset",
  soMapListFilterSortPresets: "so_map_list_filter_sort_presets",
  soMapListFilterSortActivePreset: "so_map_list_filter_sort_active_preset",
  homeAssignmentsAccordion: "home_assignments_accordion",
  homeEventsAccordion: "home_events_accordion",
  homeToolsAccordion: "home_tools_accordion",
  quickLinksFabVisible: "quick_links_fab_visible",
  myMapsAccordion: "my_maps_accordion",
  recentMapsAccordion: "recent_maps_accordion",
  authUsersActiveOnly: "auth_users_active_only",
  secretaryToolsInactiveAccordion: "secretary_tools_inactive_accordion",
  ministryReportForm: "ministry_report_form",
  ministryTimeSettingsAccordion: "ministry_time_settings_accordion",
  avSmsTemplate: "av_sms_template",
  weekendMeetingSmsTemplate: "weekend_meeting_sms_template",
} as const;

export const localStorageKeyWithVariant = (
  key: keyof typeof localStorageKeys,
  variant: string,
): string => `${localStorageKeys[key]}:${variant}`;
